// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BCollapse: typeof import('bootstrap-vue-3')['BCollapse']
    BFormCheckbox: typeof import('bootstrap-vue-3')['BFormCheckbox']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    BFormTextarea: typeof import('bootstrap-vue-3')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-3')['BInputGroup']
    BInputGroupAppend: typeof import('bootstrap-vue-3')['BInputGroupAppend']
    BNavbar: typeof import('bootstrap-vue-3')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-3')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-3')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-3')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-3')['BNavItem']
    Icon: typeof import('./src/components/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
