# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: chialab/php:7.3

# Select what we should cache between builds
cache:
  paths:
  - vendor/
services:
  - redis:latest

before_script:
  - composer install
  - php -S localhost:9000 -t public >/dev/null 2>/dev/null &

test:
  script:
  - php update.php
  - php test.php
